version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=kaartdijin_boodja
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-django-insecure}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db:5432/kaartdijin_boodja}
    ports:
      - 8000:8000

volumes:
  db:
    driver: local
