# Generated by Django 3.2.16 on 2022-10-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogueentry',
            options={'verbose_name': 'Catalogue Entry', 'verbose_name_plural': 'Catalogue Entries'},
        ),
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'verbose_name': 'Email Notification', 'verbose_name_plural': 'Email Notifications'},
        ),
        migrations.AlterModelOptions(
            name='layerattribute',
            options={'verbose_name': 'Layer Attribute', 'verbose_name_plural': 'Layer Attributes'},
        ),
        migrations.AlterModelOptions(
            name='layermetadata',
            options={'verbose_name': 'Layer Metadata', 'verbose_name_plural': 'Layer Metadata'},
        ),
        migrations.AlterModelOptions(
            name='layersubmission',
            options={'verbose_name': 'Layer Submission', 'verbose_name_plural': 'Layer Submissions'},
        ),
        migrations.AlterModelOptions(
            name='layersubscription',
            options={'verbose_name': 'Layer Subscription', 'verbose_name_plural': 'Layer Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='layersymbology',
            options={'verbose_name': 'Layer Symbology', 'verbose_name_plural': 'Layer Symbologies'},
        ),
        migrations.AlterModelOptions(
            name='webhooknotification',
            options={'verbose_name': 'Webhook Notification', 'verbose_name_plural': 'Webhook Notifications'},
        ),
    ]
